apiVersion: v1
kind: Service
metadata:
  name: rebase-bot
  namespace: github
spec:
  type: LoadBalancer
  selector:
    run: rebase-bot
  ports:
    -
      protocol: "TCP"
      port: 80
      targetPort: 8080
